### ISSUE TITLE
Hunters and Medic shotguns

### ISSUE THREAD

**Issue by duralakun** [yavl/teeworlds-infclassR#102]
Right now a hunter will not be influenced by the pullback of a medic shotgun.
Every other zombie will be thrown trough the air but it will have no affect on the hunter class.
I think this is not good, because many people dont know about it and it makes it so that as medic you need to get lucky that you not encounter hunters. 

I would like that the hunter is equally effected by the medic shotgun, therefore nerf the pullback of the shotgun a bit. And maybe give hunter a tiny speed buff to its movement.

**Comment by bretonium** [comment]
I am strongly against it.

Right now hunter and medic is one of the best parts of the game, because it perfectly fits its place in rock-paper-scissors-like system. Hunter kills medic -> Medic kills (or heal after) smokers -> Smoker kills soldier (who always has health problems because of bombs) -> soldier kills hunters.

Another absolutely cool system is ninja-bat-(looper or merc) trio. Average ninja cannot do much against average bat and can survive only if merc helps them in the skies, or if looper kills bat early.

Another cool system is engineer-boomer-looper. Engineer cannot do much when boomers run into walls frequently and on high speed - they just fail to rebuild the walls. Great example is bottom passage on `infc_eidalfitr`. Looper enormously helps by placing their long-running wall before engie wall.

Infclass is not a single-player game. Humans must form teams where members act where they are strong and rely on help where they are weak. Single players must not survive (except, maybe, heroes). If humans fail to form a team, pick right classes and build good processes, they lose.

**Comment by duralakun** [comment]
If you dont like it than i will not make a pr for this, but i still dont like it :P
If there are 4 zombies and 2 humans and you are medic, you might get lucky and there are no hunters.
Or you might get unlucky and there are 4 hunters.

**Comment by teoman002** [comment]
I also disagree with this request.
This is a feature and it works very well.
