### ISSUE TITLE
Invulnerability inside spawn

### ISSUE THREAD

**Issue by ResamVi** [yavl/teeworlds-infclassR#165]
There was one stitch fanboy on discord complaining about the spawn killing.
He has a point: youre a newcomer and spawn on infc_toilet/infc_warehouse2 and you dont get to play the game.

This will have major balance implications though, so I wanted to hear your opinion first

**Comment by teoman002** [comment]
I suggest to activate a no damage mode after zombies have spawned.
The time has to be tested but I guess 1.5 to 2.5 seconds are enough for them to move outside the lethal damage zone.
However, I do not recommend to make the spawn entirely protected, due to changes of the playing dynamic that come with it. For instance, humans need to stay at least one hook length away from zombies at spawn all the time, due to invincible zombies.

**Comment by NewRedsquare** [comment]
I think that there was such of similar feature before on stitch626's server ?
