### ISSUE TITLE
breton

### ISSUE THREAD

**Issue by duralakun** [yavl/teeworlds-infclassR#31]
You complain about me, but at same time you push changes that you dident even compile:
https://github.com/yavl/teeworlds-infclassR/commit/b64133d611c24e85dab6bf1438f0113eea006ca4
https://github.com/yavl/teeworlds-infclassR/commit/8879a3b3c00423240495ac87077bd913046a3474
typos dont compile, and where are the reviews?

**Comment by bretonium** [comment]
I agree, that was bad. That is exactly the moment when i realized that my typos and mistakes can affect many people who are developing stuff. That is specifically the reason why i vouch for using branches and pull requests together with code review.

I fixed the typos you are mentioning and i don't see a bug here. If you have a problem with me personally, please contact me by email or in the game so that we could resolve it.
