### ISSUE TITLE
Why King is bad

### ISSUE THREAD

**Issue by duralakun** [yavl/teeworlds-infclassR#43]
How the King works:
X people have to write /king and 1 human randomly becomes the King.
The King has a passive heal aura, that heals humans in a certain range.
The King also makes wall of engineers last longer.
The King only has a hammer as weapon.
If the King dies all humans get damaged and walls might break.

Why the King is bad:
Playing as King is boring, you only have a hammer and you cant do much.
You didn't choose to become King but you were forced to play it.
Waiting as zombie in front of an engineer wall is boring, you cant do much.
Making the walls last longer makes it worse.
Passive heal is also boring, you as king don't have to do much to heal, and it allows humans to do more mistakes / get less punished for mistakes. Or in other words zombies get less rewarded for good play.
I don't want to lose health or my wall only because another human died. Maybe I am on the opposite side of the map and couldn't do anything to protect the King, or the King was stupid and just committed suicide, or maybe the King is just afk and its impossible to protect him.
That players have to write /king is not intuitive or fun. It would be better if the king was summoned if the humans made some sort of ritual or idk.

**Comment by bretonium** [comment]
OK, first of all, king is not ready. It is not merged to master yet and author afaik acknowledged that there is still a lot of work to do.

Second, i agree. Becoming a king is pretty unrewarding right now. I disagree with some of the points, for example, involuntariness of the switch or walls destruction, because it is the same with witch and is fun. But existing as king is boring right now.

>  That players have to write /king is not intuitive or fun. It would be better if the king was summoned if the humans made some sort of ritual or idk.

Same about witch. There was an idea to perform "witch ritual", but it was not implemented. Another thing i started implementing but failed due to lack of time is red flags on the maps for zombies to find. I don't know what the ritual could be for king.

**Comment by duralakun** [comment]
Please don't see this an insult, i just wanted to give my opinion about it. I also think that it would be much better if there was a witch ritual instead of /witch.
