### ISSUE TITLE
nerf engineer wall even more

### ISSUE THREAD

**Issue by teoman002** [yavl/teeworlds-infclassR#74]
The stats show that engineer is still op.
https://stats.resamvi.de/#/
Most kills, most picked, most survived, most alive

**Comment by duralakun** [comment]
I suggested some time ago to make it so:
- Each zombie that dies inside the wall takes away 5-10 seconds of the wall. (instead of 2 or 3 right now)
- Therefore we make the laser rifle more fun to play with

**Comment by duralakun** [comment]
If we nerf engineer, than i think we need to buff other classes that are weak now, a bit. Like ninja #65

**Comment by teoman002** [comment]
@bretonium can you do that?

**Comment by bretonium** [comment]
I think engineer is good as it is now. I don't see anything bad in the fact that people choose engineer more and that engineer has more kills (especially given that number of kills is a bad metric that should rarely be paid attention to). Also engineer is not most alive (what does that metric even mean?)

Engineers are the keystone of human defense. All defense builds up around engineers. Want to remove that keystone? Offer something else. Otherwise we shall fall back to super-low human win rate as it was on some servers.
